### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kasia1403** [Asek3/Rubidium#108]
Port to 1.12.2 ASAP !

**Comment by SpinHarmony** [comment]
It is extremely unlikely that this will ever be ported to 1.12.2. The mod this is forked from (Sodium) was not available in that version, and there have been many changes to Minecraft since then that would make backporting it very difficult. Furthermore, there are also already many other performance mods in 1.12.2, so it’s not really that necessary.

Also, 1.12.2 is a largely abandoned version that very few mods still support, and most newer mods are exclusively in newer versions, and many of the old ones have updated now. Unless there is a specific mod you want to play that’s not in newer versions, I would recommend updated to at least 1.16.5, as that version has the most mods on Curseforge.

**Comment by Kasia1403** [comment]
I want to play with Mniecraft 1.12.2 mods, because Dr Zhark's Mo' Creatures mod is still not updated. Maybe could You talk with Dr Zhark andask him if he will update Mo' Creatures and when ?

**Comment by Asek3** [comment]
no

**Comment by SpinHarmony** [comment]
> I want to play with Mniecraft 1.12.2 mods, because Dr Zhark's Mo' Creatures mod is still not updated. Maybe could You talk with Dr Zhark and ask him if he will update Mo' Creatures and when ?

While I realize it’s not exactly the same thing, maybe you could try Alex’s Mobs instead. It has a similar premise and is available for 1.16+. The Curseforge page is here: [https://www.curseforge.com/minecraft/mc-mods/alexs-mobs](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
