### ISSUE TITLE
1.18.2 CTM Chunk Update Incompatability

### ISSUE THREAD

**Issue by Tohricat** [Asek3/Rubidium#160]
![image](https://user-images.githubusercontent.com/53372339/174321447-5111742a-eaf0-411c-9be8-4ab1aeeec7e8.png)
![image](https://user-images.githubusercontent.com/53372339/174321506-3483d895-e74a-40b7-a694-5e632a4845ac.png)

Chunk updates cause connected textures to randomly shift their connections.

**Comment by Tohricat** [comment]
F3+A (reloading the chunks) fixes the issue, and any CTM blocks placed will look as they should and won't change with any chunk updates. New blocks placed will have the issue though.

**Comment by xameryn** [comment]
Having the same issue with Timber Frames and CTM

Before reloading chunks (F3+A or relogging):
![image](https://user-images.githubusercontent.com/11352382/175796329-a1a8c9d9-3806-4e6a-94d5-cf8dbe9dbf37.png)

After reloading chunks:
![image](https://user-images.githubusercontent.com/11352382/175796332-680586f1-d8d0-4a73-9a7c-b1f1cc27e627.png)

CTM Version: 1.18.2-1.1.4+4
Rubidium Version: 0.5.2a

**Comment by SDUBZ** [comment]
i think you guys should tell the ctm author becuase i was having issues myself and removed it and never had those issues with crashes etc

**Comment by xameryn** [comment]
This bug doesn't cause crashes as far as I'm aware, only the visual connection issues, and removing it defeats the purpose as connected textures won't work without it.

**Comment by paradoxuum** [comment]
This appears to be caused by an issue in `WorldSlice`. Creating a new `WorldSlice` in `ChunkRenderCacheLocal#init`  fixes this issue, though this would probably result in a fairly significant performance impact and an increase in memory usage. My guess is that the connected texture states aren't being saved or looked up correctly, or something along those lines.

This at least explains why it's fixed when reloading chunks, because new `WorldSlice` instances are created.
I'll try to look into this more to see if it can be resolved, or if I can at least add more onto this issue.

Strangely enough, Connected Glass Mod works perfectly fine with Rubidium, so my only assumption is that something weird is happening with the way CTM handles block states, or at least the way it's stored in `WorldSlice`; it's hard to tell so far.

**Comment by embeddedt** [comment]
I think I have tracked down the cause of this. https://github.com/Chisel-Team/ConnectedTexturesMod/issues/168#issuecomment-1696176633

**Comment by mikeprimm** [comment]
@embeddedt I tried out your fix, and it looks good - but, it looks like the 1.18.2 Oculus hacks a coremod into the performBuild and gets tripped up by the local variable frame change.   I came up with a slightly modified version that seems to avoid this problem, while still yielding the needed fix - 
https://github.com/Asek3/Rubidium/compare/1.18/dev...mikeprimm:Rubidium:1.18/dev

**Comment by embeddedt** [comment]
@mikeprimm Thanks for testing this and the note. I will go back and adjust the patches on all versions to not alter the LVT.
