### ISSUE TITLE
Crashes with BetterEnd Forge.

### ISSUE THREAD

**Issue by MagmaSlime123** [Asek3/Rubidium#194]
See the report. Mods, etc. are in there. Thank Forge.

[crash-2022-07-14_22.12.32-client.txt](https://github.com/Asek3/Rubidium/files/9117707/crash-2022-07-14_22.12.32-client.txt)

**Comment by Asek3** [comment]
Update BetterEnd https://www.curseforge.com/minecraft/mc-mods/betterend-re-forked/files

**Comment by MagmaSlime123** [comment]
Read the report. I was using 1.16.5, and the latest 2.5 version of the mod.

**Comment by aethaerya** [comment]
No, you weren't.
![image](https://user-images.githubusercontent.com/28931355/179858584-70989cba-4348-42a7-b510-6e6fbe2f7000.png)

![image](https://user-images.githubusercontent.com/28931355/179858655-a98e89cf-b4cd-4ca3-8c2e-db8ce0526302.png)

**Comment by LiVeenMusic** [comment]
Currently experiencing the same issue, after double, triple and quadruple checking that I'm on latest 1.16.5 oculus, rubidium, better end reforked (not official forge port) 2.5.
Would also like to note that reforked does not appear anywhere in logs, nor in crash reports. It appears as betterendforge 1.16.5-2.5, so searching for reforked does not do you any good, and is not sufficient to disprove an issuant's claim, as you would have found out by discovering that you can't find it in your own logs either. hell, when you download the mod the filename is even betterendforge. This is so frustrating to me, because every single issue related to loading into the world is immediately closed with this response now, and it makes me wonder how many of those people already were on reforked instead of forge, but got shut up before sufficient help was provided.

**Comment by MagmaBro123** [comment]
Both BetterEnd Reforked and BetterEnd Forge have this exact same issue. This isn't my fault.

**Comment by MagmaSlime123** [comment]
> Currently experiencing the same issue, after double, triple and quadruple checking that I'm on latest 1.16.5 oculus, rubidium, better end reforked (not official forge port) 2.5. Would also like to note that reforked does not appear anywhere in logs, nor in crash reports. It appears as betterendforge 1.16.5-2.5, so searching for reforked does not do you any good, and is not sufficient to disprove an issuant's claim, as you would have found out by discovering that you can't find it in your own logs either. hell, when you download the mod the filename is even betterendforge. This is so frustrating to me, because every single issue related to loading into the world is immediately closed with this response now, and it makes me wonder how many of those people already were on reforked instead of forge, but got shut up before sufficient help was provided.

@ChrisRonaasen 

Both BetterEnd Reforked and BetterEnd Forge have this exact same issue with this mod, and this isn't my fault either. Both forks are dead, and I already opened an issue on there. Nothing since.

I hate talking about this stuff, but...

I really wish there was an actual active BetterEnd port on Forge. It really saddens me how little people care about porting
mods, despite there being tools out there that can help a bit. Heck, even the original Sodium and Iris could've used Architectury API or other tools to make development a bit easier so both loaders can enjoy the mod.

**Comment by LiVeenMusic** [comment]
@MagmaBro123 
With you on that one for sure. I wouldn't force a developer to make a mod for both loaders, but honestly, they could still keep in mind during the design that other people WILL try to port it if they like the mod enough, and thus choose some things based off of that. If it's too much work (I'm not a dev so I can't speak on that), then I wouldn't expect them to do it, but the little things, the easy choices between A or B etc; those ones could really be chosen based off of expandability and portability. It puts your mod in front of more people's eyes (WITHOUT those people thinking you have to fix their problems, because it's the port author's problem), and aside from just sheer exposure, it means that a mod as useful as for example Rubidium and Oculus, these are practically the only two options available now for an alternative rendering engine that boosts performance so much that shaders become very playable even with large modpacks deep into playthroughs.

But, alas, idk about you, but I'm not a developer. Overall, I'm still super grateful to Asek3, and to the authors of all the relevant mods (mostly Asek3 and the Iris dev though) because even with the annoying bugs, and the crashes I get if I use the latest versions of Rubi+Ocu, the non-crashing but buggy versions still improve my frames with shaders so damn much that I can actually stay interested and engaged in playing, deep into a world.
So thank you @Asek3 , thank you Iris devs, and thank you to all the others.

But also, please, please do try to help those of us who have crashes (without crash reports, only latest.logs to provide) with the latest versions on certain modpacks. hell, it might be an AMD GPU specific issue. I'll find that one out later today when I test this on my GFs PC. While we're grateful, we're also really wanting to get some support, some attention. I just feel bad asking for help, when they do this for free with their own time, they're just being nice. But I can't fix this myself, so what can I do

**Comment by MagmaBro123** [comment]
I also agree. But I wish mods like the original Sodium and Iris could've used Architectury API or other tools to make development a bit easier so both loaders can enjoy the mod.

If you do do ever figure out what causes this BetterEnd crash, you could probably PR a fix for it for 1.16.5.

> @MagmaBro123 With you on that one for sure. I wouldn't force a developer to make a mod for both loaders, but honestly, they could still keep in mind during the design that other people WILL try to port it if they like the mod enough, and thus choose some things based off of that. If it's too much work (I'm not a dev so I can't speak on that), then I wouldn't expect them to do it, but the little things, the easy choices between A or B etc; those ones could really be chosen based off of expandability and portability. It puts your mod in front of more people's eyes (WITHOUT those people thinking you have to fix their problems, because it's the port author's problem), and aside from just sheer exposure, it means that a mod as useful as for example Rubidium and Oculus, these are practically the only two options available now for an alternative rendering engine that boosts performance so much that shaders become very playable even with large modpacks deep into playthroughs.
> 
> But, alas, idk about you, but I'm not a developer. Overall, I'm still super grateful to Asek3, and to the authors of all the relevant mods (mostly Asek3 and the Iris dev though) because even with the annoying bugs, and the crashes I get if I use the latest versions of Rubi+Ocu, the non-crashing but buggy versions still improve my frames with shaders so damn much that I can actually stay interested and engaged in playing, deep into a world. So thank you @Asek3 , thank you Iris devs, and thank you to all the others.
> 
> But also, please, please do try to help those of us who have crashes (without crash reports, only latest.logs to provide) with the latest versions on certain modpacks. hell, it might be an AMD GPU specific issue. I'll find that one out later today when I test this on my GFs PC. While we're grateful, we're also really wanting to get some support, some attention. I just feel bad asking for help, when they do this for free with their own time, they're just being nice. But I can't fix this myself, so what can I do

I also agree. But I wish mods like the original Sodium and Iris could've used Architectury API or other tools to make development a bit easier so both loaders can enjoy the mod.

If you do do ever figure out what causes this BetterEnd crash, you could probably PR a fix for it for 1.16.5.

**Comment by MagmaSlime123** [comment]
> @MagmaBro123 With you on that one for sure. I wouldn't force a developer to make a mod for both loaders, but honestly, they could still keep in mind during the design that other people WILL try to port it if they like the mod enough, and thus choose some things based off of that. If it's too much work (I'm not a dev so I can't speak on that), then I wouldn't expect them to do it, but the little things, the easy choices between A or B etc; those ones could really be chosen based off of expandability and portability. It puts your mod in front of more people's eyes (WITHOUT those people thinking you have to fix their problems, because it's the port author's problem), and aside from just sheer exposure, it means that a mod as useful as for example Rubidium and Oculus, these are practically the only two options available now for an alternative rendering engine that boosts performance so much that shaders become very playable even with large modpacks deep into playthroughs.
> 
> But, alas, idk about you, but I'm not a developer. Overall, I'm still super grateful to Asek3, and to the authors of all the relevant mods (mostly Asek3 and the Iris dev though) because even with the annoying bugs, and the crashes I get if I use the latest versions of Rubi+Ocu, the non-crashing but buggy versions still improve my frames with shaders so damn much that I can actually stay interested and engaged in playing, deep into a world. So thank you @Asek3 , thank you Iris devs, and thank you to all the others.
> 
> But also, please, please do try to help those of us who have crashes (without crash reports, only latest.logs to provide) with the latest versions on certain modpacks. hell, it might be an AMD GPU specific issue. I'll find that one out later today when I test this on my GFs PC. While we're grateful, we're also really wanting to get some support, some attention. I just feel bad asking for help, when they do this for free with their own time, they're just being nice. But I can't fix this myself, so what can I do

I also agree, but Sodium and Iris could've used Architectury API or other tools so both loaders can enjoy the mod. But apparently not. If you do ever figure out this BetterEnd crash though, you could PR a fix, or just make an actual active BetterEnd fork..
