### ISSUE TITLE
(1.19.2) java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16385

### ISSUE THREAD

**Issue by eithli** [Asek3/Rubidium#289]
https://pastebin.com/raw/MrNn1tKe

Game crashes after a while of playing, it isn't a set time either. Sometimes it'll take an hour before it crashes, sometimes it'll take 10 min.

**Comment by coderepo8593** [comment]
You need to post the crash report. The log, while important, doesn't give all the necessary information to troubleshoot. 

Since this is something that is happening sporadically, it likely has something to do with loading a particular chunk with modded elements, a modded entity, or modded action/effect associated with an entity.

This is a common exception and in my experience, it is likely due to an incompatibility with another mod.

**Comment by Coraline774477** [comment]
I've just experienced this crash but different mod list.
But which mod is causing the incompatibility in my 1.19.2 mod lists (especially my latest one) as well as @eithli's mod list?
Since I don't really have the time to sift through my mod lists to find the incompatibilities with Rubidium...

I could send my current mod list to you @coderepo8593* to decipher through it to find out which one's are causing this.
(*Why I'm mentioning you coderepo is cause you might help me as well as many others find out which mods are incompatible with Rubidium since OptiFine can just go suck it since OptiFine is the worst performance mod in history!..)

Btw I've been thinkin just now and I think that Farmer's Delight might not be truly compatible with Rubidium since F.D adds custom "wild" plants to the world-gen..

**Comment by Lucky-56** [comment]
got the same issue here
https://crashy.net/Eg0RXcKyyAi3tYS7pLuO

**Comment by Asek3** [comment]
Fixed in 0.6.2a
