### ISSUE TITLE
Custom Model texture does not load when using Rubidium

### ISSUE THREAD

**Issue by coaber** [Asek3/Rubidium#303]
sums it up in the title, i've created a custom block(sphere) with a .obj model which has only a base black color as texture, but for some reason whenever rubidium is installed it fails to load in the texture and the block (sphere) is white. Messing with the options inside the video settings does nothing, and this is on all versions up to the newest one

tested on FML 40.1.45, 1.18.2
tested initially on 0.5.2a up to newest one for 18.2

**Comment by coderepo8593** [comment]
You are providing a problem that is inscrutable to troubleshooting. Without providing the exact steps you took or process, there is no way to discern the cause of the problem absent there already being some known problem with Rubidium itself that would cause this behavior to occur. 

Considering that other mods are able to use custom blocks and textures with Rubidium without issue, this should give you pause and prompt you to further consider what it might be that is different in what you are doing that they are not. It might very well be something is wrong with Rubidium here and you have stumbled upon some scenario that results in a bug, but this scenario would still be unique and particular to the circumstances created by your mod.

In order for this problem to be investigated, you need to do the following:
1. Provide the steps and process I can take to reproduce this error. Merely creating a custom block and texture is not it, because people do this all day and every day and yet Rubidium has no problems with those mods.
2. Make your code publicly available on github via a repo or provide a GIST with the significant and most relevant code.

**Comment by coaber** [comment]
Apologies for the late reply. The mod was made trough MCreator, which *may be a problem, but to my knowledge it does not seem to misbehave at all when running a basic forge client with nothing on it. even my modpack without any optimization mods installed rendered the model file just fine (which in this case is a OBJ+MTL type, which was made in Blender, and all it has is a basic black texture). I will provide a archive of the project if you're willing to take a look, since the git did not let me upload all the files at once, and doing it manually will likely take forever.
https://drive.google.com/file/d/1wrzwQTcKaSmI4BwU5XrroWYOziTyOHkv/view?usp=sharing

**Comment by coaber** [comment]
Slight update, i messed around in blender some more, and decided to add some custom mapping to the model off a base texture, which now renders correctly in game while using rubidium. Closing
