### ISSUE TITLE
Incompatibility with NoCubes

### ISSUE THREAD

**Issue by uhloin** [Asek3/Rubidium#436]
Rubidium for 1.19.2 (rubidium-0.6.2.jar) with nocubes crushes again.
Line "mixin.features.chunk_rendering=false" does not help both in file rubidium.properties and rubidium-mixins.properties.

Previous issue (closed):
https://github.com/Asek3/Rubidium/issues/81
Also see pull request
https://github.com/Asek3/Rubidium/pull/408
More crushlogs in issue for NoCubes:
https://github.com/Cadiboo/NoCubes/issues/88

[crash-2023-03-17_09.40.10-client.txt](https://github.com/Asek3/Rubidium/files/10998193/crash-2023-03-17_09.40.10-client.txt)

**Comment by DataDalton** [comment]
Can confirm crashing with:
Forge 43.2.8
Rubidium 0.6.2 
NoCubes 1.19.1-0.5.0-dev-2b0e776 (CurseForge has it marked as 1.19.2)
Prism logs: [https://mclo.gs/kTBraSZ](https://mclo.gs/kTBraSZ)

With newest, it still crashes:
Forge 43.2.8
Rubidium 0.6.2a
NoCubes 1.19.3-0.5.0-dev-bd204a0 and 1.19.1-0.5.0-dev-2b0e776 (Tested both versions because they're both marked compatible with 1.19.2 which is weird how they marked/titled it)
Prism logs: [https://mclo.gs/huH2xqK](https://mclo.gs/huH2xqK)

**Comment by Asek3** [comment]
Fixed in dev version
