### ISSUE TITLE
Occultism multiblock preview does not show up

### ISSUE THREAD

**Issue by Silverseppel** [Asek3/Rubidium#449]
Hi,
the multiblock preview of Occultisem is not show up and the dev says its an issue in Rubidium. Can you please fix it

[https://github.com/klikli-dev/occultism/issues/894](https://github.com/klikli-dev/occultism/issues/894)
[https://github.com/klikli-dev/occultism/issues/873](https://github.com/klikli-dev/occultism/issues/873)

**Comment by klikli-dev** [comment]
This seems to be due to Rubidium skipping/disabling certain RenderStages.
I added a workaround to modonomicon to render on a different stage when rubidium is present, this limits multiblock previews to "fancy" render settings though as it seems all the non-fancy stages are skipped.

The workaround is added in https://github.com/klikli-dev/modonomicon/commit/4103ac9a0c477caa1ec69ab000108368d3c49b65

As of 1.19.4. it works automatically without modification of modonomicon, presumably because the rewrite/new port from sodium accounts for the new forge render system fully.

**Comment by Asek3** [comment]
Now should be fixed on our side
