### ISSUE TITLE
Rendering Issue in 1.19.4, transparent holes in the world made up of invisible blocks

### ISSUE THREAD

**Issue by Devilswarchild** [Asek3/Rubidium#488]
MC 1.19.4
Forge: 45.0.57

rendering issue resolves itself when I set rubidium as disabled in my instance launcher via curseforge.

steps to produce use my modpack and load into a world and just look around till you find what looks like a "hole" in the world

![Screenshot_1](https://user-images.githubusercontent.com/27385258/236925995-57587cdc-2c7b-4a99-a8a0-71a1a4af0fa8.jpg)

![image](https://user-images.githubusercontent.com/27385258/236926547-ebf70690-04ab-49f8-bc51-ab484404d63d.png)

here are as many logs as I can think to attach 

[debug.txt](https://mclo.gs/mHhrJvl)

[latest log.txt](https://mclo.gs/DbvVrlS)

[launcher_log.txt](https://mclo.gs/tey3Lie)

not sure what the issue is really, all I know is that when rubidium is on the error in the screenshots appear, when I turn it off they disappear.

**Comment by Re-VelatoR** [comment]
Turn biome blend down to 0

**Comment by Devilswarchild** [comment]
ha! that fixed it. nice. thank you very much. is this a permanent fix though?

**Comment by Re-VelatoR** [comment]
Yes, as far as I can tell. You'll need to wait for a Rubidium update that fixes it and allows you to use biome blending again, if that's an important feature at all to you

**Comment by Devilswarchild** [comment]
that very much is as it makes the biome merging much smoother looking

**Comment by Re-VelatoR** [comment]
You can try using the Better Biome Blending mod. It's only updated up to 1.19.0, but it might be forward compatible like Starlight is (which is currently only listed as 1.19.3). I can't guarantee its compatibility with Rubidium, but the mod does a complete replacer of the default biome blend and works up to 29x29. Because it's a replacer, it might work without having the render holes, if it works at all. I'm not at home so I am unable to test it myself currently

**Comment by Devilswarchild** [comment]
might have to wait on that to get updated lol

**Comment by Kasualix** [comment]
https://github.com/Asek3/Rubidium/pull/475

**Comment by Asek3** [comment]
1.19.4 is abandoned, try https://drive.google.com/file/d/1Y2rUojTOgOq2gWL0T2fsgqRGLuzw89Si/view?usp=sharing
