### ISSUE TITLE
CTM broken with rubidium

### ISSUE THREAD

**Issue by phoenixxempire** [Asek3/Rubidium#510]
I think this is a known issue, but it would be helpful because wonderful building mods like Chipped 2 cannot run without CTM, and I cannot handle the FPS drops incurred by doing the fix in the mixin properties.

**Comment by katubug** [comment]
https://github.com/Asek3/Rubidium/issues/69
https://github.com/Chisel-Team/ConnectedTexturesMod/issues/168

Some related issues. I came here as well, hoping for a response to this apparently long-lived issue. I would like to include Chipped in my Cottage Witch Recast modpack, but I am unwilling to remove Rubidium and Oculus because they are just too good. I am not looking forward to getting a ton of reports of incorrect textures, haha. So any help would be appreciated!

For me this is occurring on -
Minecraft 1.19.2
Forge 43.2.11
Rubidium 0.6.2b
CTM 1.1.6+8

Thanks for your time!

**Comment by villainous-j** [comment]
would be awesome to see this fixed!

**Comment by loldev69** [comment]
#160 appears to have fixed the issue, as far as I could test, but the relevant commit hasn't been included in any update yet except for the 1.16 one (Rubidium mc1.16.5-0.2.13).
You can still grab the autogenerated builds from the Actions, I used https://github.com/Asek3/Rubidium/actions/runs/6130488996 for testing: and yes, it's named 0.5.6 like the 0.5.6 release but it's not the same file, it's a bit confusing.

**Comment by Asek3** [comment]
1.16.5 and 1.19.2 versions was fixed

**Comment by LandofHeros2234** [comment]
Still affects 1.18.2

**Comment by GordonRamsay20** [comment]
When will this issue be fixed on 1.18.2?

**Comment by loldev69** [comment]
@LandofHeros2234 @GordonRamsay20 the fix is in the dev builds together with many others, but for some reason there hasn't been a new release for 1.18 since April 17 aka [this commit](https://github.com/Asek3/Rubidium/commit/8bb8de0fb32381d3eee1c844a3f96e98926b7ae8).
@Asek3 maybe there's some CI/CD pipeline issue?
