### ISSUE TITLE
Project Red/ CB Multipart graphical issue again

### ISSUE THREAD

**Issue by default-dx** [Asek3/Rubidium#515]
Rubidium Version: 0.5.6, Newest version of project red on 1.18
Fixed on 1.16.5 but reappeared in 1.18
![2023-06-25_10 16 24](https://github.com/Asek3/Rubidium/assets/61863055/e1cd6d0a-afe5-4a95-b275-b6537989c656)

**Comment by Chassx2** [comment]
Just posted about this on their issue board as well. Can't wait to get this resolved.

**Comment by MrTJP** [comment]
Basically a case of 2 hacks not being compatible. Likely an easy solution to this. Providing some info here for context.

CBMultipart uses CodeChickenLib's `CCBlockRenderer` mechanism to render its multipart blocks. It's basically a hook that allows programmatic level rendering instead of MC's default json-based block model system. 

The hook is based on an object wrapper rather than, say, a mixin. `Minecraft#blockRenderer` is replaced with a `CCBlockRenderingDispatcher`, which is a wrapper that will intercept calls to `renderBatched` and try to find a registered renderer first, otherwise delegate to the original blockRenderer instance. 

You can find the initialization code [here](https://github.com/TheCBProject/CodeChickenLib/blob/49f0d28d19b7cd87d046b0ebd763c9440ff3681e/src/main/java/codechicken/lib/render/block/BlockRenderingRegistry.java#L38) and the actual wrapper class [here](https://github.com/TheCBProject/CodeChickenLib/blob/49f0d28d19b7cd87d046b0ebd763c9440ff3681e/src/main/java/codechicken/lib/render/block/CCBlockRendererDispatcher.java#L53).

**Comment by pcking99** [comment]
Following. Any updates?
Rubidium: 0.5.6
Oculus: 1.18.2-1.6.4

**Comment by Asek3** [comment]
Fixed in Dev version

**Comment by VirtualGaming1** [comment]
@Asek3 still waiting for it to be fix in 1.18.2 version

**Comment by qznfbnj** [comment]
> @Asek3 still waiting for it to be fix in 1.18.2 version

How about [Embeddium](https://github.com/embeddedt/embeddium/wiki/Changelog#024)? 
Download: [CurseForge](https://www.curseforge.com/minecraft/mc-mods/embeddium/files/4862488) / [Modrinth](https://modrinth.com/mod/embeddium/version/0.2.9+mc1.18.2)
