### ISSUE TITLE
Crash Forge 1.20.1 - 47.1.3

### ISSUE THREAD

**Issue by Mjolinir** [Asek3/Rubidium#547]
Greetings,
MC 1.20.1
Forge 47.1.3
Rubidium 0.7.0

[latest.log](https://github.com/Asek3/Rubidium/files/12267556/latest.log)

Game crashes on startup. Possibly same issue as #543 , the error is similar but a bit different.

**Comment by DiogoHSS** [comment]
Same as me, latest.log will say some mod failed loading becase it was too early (in my case happened with modernfix and after disabling modernfix it them said ftbchunks failed loading) but when disabling OR DOWNGRADING from rubidium-mc1.20.1-0.7.0.jar to rubidium-0.6.5.jar it works with booth modernfix and ftbchunks activated, so I guess it was the latest update.

**Comment by sandalle** [comment]
https://github.com/embeddedt/ModernFix/issues/201 notes the issue and fix:
> One of your other mods loads a Minecraft class too early, which is bad practice and causes compatibility issues with other mods (like ModernFix). Please try to isolate which other mod is the culprit.

Downgrading from Rubidium 0.7.0 to 0.6.5 on MC 1.20.1 with Forge 47.1.3 allows my client to start again.

**Comment by Coraline774477** [comment]
Just a suggestion, but we all should just go back to either 1.19.4 or even better 1.19.2. Since Rubidium 1.19.2 doesn't behave the same like it's newer versions does. If yall would like to come take a look at my issue report from a month ago (#529)*. Which is why I've decided to put 1.20.1 on hold for a little while longer than expected cause of Rubidium 1.20.1 malfunctioning/not working properly (for some people like me that is).

Again just a suggestion that doesn't fix the problem but it's an alternative to wait out the issues that Rubidium 1.20.1 has till @asek3 fixes/polishes Rubidium 1.20.1 a little bit more after the Sodium peeps does the same thing with Sodium 1.20.1. Just like what I'm currently doing right now which obviously the latest update for Rubidium 1.20.1 is still unstable in my eyes...

*Which btw I'm still waiting for him to review my issue report, I get it that he's busy with other things as well as Rubidium but could he speed up the process just a little bit? Please?...

(Like as if I would like to come back to 1.20.1 when a few of the mods that I play with in 1.19.2 haven't been ported over to 1.20.1 yet. So I'm actually not in a rush for him to fix/polish Rubidium 1.20.1)
