### ISSUE TITLE
Minecraft crashes upon startup w/ Rubidium installed/enabled

### ISSUE THREAD

**Issue by Ereshkigal101** [Asek3/Rubidium#59]
[latest.log](https://github.com/Asek3/Rubidium/files/8422230/latest.log)
[debug.log](https://github.com/Asek3/Rubidium/files/8422231/debug.log)
Minecraft Version 1.18.1

**Comment by theDFitz** [comment]
I am having a similar issue, I believe
[latest.log](https://github.com/Asek3/Rubidium/files/8422489/latest.log)
[debug.log](https://github.com/Asek3/Rubidium/files/8422498/debug.log)
.

My game version is 1.18.1, not sure if that's necessary to mention but figured better to be safe than sorry. 

(edit)

Alright, am I just dumb? Is Rubidium not a server-side mod? Because I took it out of the server Mod-Folder and my server will load now. So either its something I'm missing with the Rubidium config/.json file(and it is a server-side mod), or I'm really stupid.

**Comment by KarinMiku** [comment]
i wouldnt use it on a server, mine didnt crash but had a lot of missing / inivisible textures, once i took it out of the server and installed it only on the client everything worked like a charm (1.16)

**Comment by Ereshkigal101** [comment]
> i wouldnt use it on a server, mine didnt crash but had a lot of missing / inivisible textures, once i took it out of the server and installed it only on the client everything worked like a charm (1.16)

I'm using it only in a Single Player world, not a server. I can't even get past the Minecraft launcher, unfortunately :(

**Comment by Asek3** [comment]
U trying to run Rubidium 1.18.2 on 1.18.1
