### ISSUE TITLE
Immersive engineering wires are invisible

### ISSUE THREAD

**Issue by Klemorius** [Asek3/Rubidium#89]
Hi, I know that you are working hard in mods compatibility but I encounter a problem where wires are not rendered.
![IEinviswires](https://user-images.githubusercontent.com/62289595/163676161-cca718b9-b75b-4712-b723-909d32d7df24.jpg)

Minecraft 1.18.2 (forge 40.0.44)
Rubidium 0.5.2a

**Comment by CanadianBaconBoi** [comment]
Related to Asek3/Oculus#135

**Comment by Esseit** [comment]
The linked issue is not relevant here, as running a game with only rubidium and IE results in the same problem, wires are then only thing not rendering it seems.

**Comment by Mykosayyad** [comment]
I had this issue with Optifine and sometimes even when I had shaders off. I still think the issue is related to performance mods though; however I'm unable to confirm this because I had this same issue for a while but I made a guess that it's because I had shaders turned on at one point. It could be because having turned on shaders at one point and then disabling them caused this issue however since that is very unlikely I think it's because Optifine/Rubidium may have just disabled certain effects/particles.

**Comment by MattB70** [comment]
It's most likely that its being culled accidentally, disabling all features doesn't help though, so it's caused by something more core.

**Comment by AtzG5O8** [comment]
I am also having this issue, with or without shaders. I have rubidium-0.5.2a and oculus-mc1.18.2-1.2.4

**Comment by deprale** [comment]
Same issue. Any fixes anytime soon? 🤙

**Comment by MrAkells** [comment]
Same issue.

**Comment by brucethemoose** [comment]
Would a log help debug this?

**Comment by brucethemoose** [comment]
Possible workaround in this thread: https://github.com/BluSunrize/ImmersiveEngineering/issues/5300#issuecomment-1139724675
