### ISSUE TITLE
Rubidium and Better Loading Screen incompatibility

### ISSUE THREAD

**Issue by yojakeo** [Asek3/Rubidium#90]
Near the point of booting to the main menu the game fails to create a fence object. I isolated the two mods just to make sure and it crashes the same way. But including both just in case.

Isolated crash (only Rubidium and BLS): https://pastebin.com/WmzLexVe
Modpack crash: https://pastebin.com/K82yhmQz

Also some insight from someone on the forge discord and they said this

"Hmm
I searched github and it seems that error is from sodium
So its rubidium erroring
https://github.com/Asek3/Rubidium/blob/f7e9885d4c266f2d218fa3aa120285ae7d3362e6/src/main/java/me/jellysquid/mods/sodium/mixin/core/MixinMinecraftClient.java#L40 
Ah, its a fence in terms of opengl, not an actual block"

**Comment by aking4125** [comment]
We're getting a similar crash report here.

[crash-2022-05-04_11.04.05-client.txt](https://github.com/Asek3/Rubidium/files/8621656/crash-2022-05-04_11.04.05-client.txt)

**Comment by sandtechnology** [comment]
It's caused by the hacky way of Better Loading Screen, it changing context on the render thread by detach and create its own context, which making this failed to execute (since it detached context this time, and there are no context to do this).
Although is the fault of Better Loading Screen, but the workaround for Rubidium is checking if context existed:
```
if (GLFW.glfwGetCurrentContext() != 0L) {
//Do something you want
}
```
And, the patched version of rubidium using this workaround is there, use at your own risk.
(You need to unzip the jar from this zip).
[rubidium-0.5.2a-patched.jar.zip](https://github.com/Asek3/Rubidium/files/9134194/rubidium-0.5.2a-patched.jar.zip)
