### ISSUE TITLE
[1.18.2] Sky/sun/cloud disseapearing when underwater

### ISSUE THREAD

**Issue by phenix60** [Asek3/Rubidium#95]
Hi, i write this because i don't know if its intended or not but i have a weird bug when using rubidium.

When i activated it rubidium make everything in the sky ( sun, cloud, even sky itself) remove from the game while i'm under water and looking to the sky .
Step 1
I took some screenshoot with pure vanilla minecraft (no mod or ressource pack or shader) like you can see on picture 1
![picture 1](https://user-images.githubusercontent.com/24650325/164261959-ea6d667e-5b41-45f9-a7f7-9271d1f1f089.jpg)
there with default minecraft while under water i can see the sun.
Step 2
I activated rubidium, and rubidium only ( still no ressource pack, no mod except rubidium, no shader ) and got this as you can see in picture 2
![avec rubidium](https://user-images.githubusercontent.com/24650325/164262834-faab6ea6-ac4e-4595-a9f0-f19f0be2ca70.jpg)
The sun already gone ( and no time hasnt change, i always use the "/time set day" command to be sure to be on the same time)
Step 3
I tried adding oculus to use the shader (i was used to on my fabric build) and got this 
![rubidium + oculus with shader](https://user-images.githubusercontent.com/24650325/164263758-d1952058-f4dd-42de-9b70-4a4cc44ccbd9.jpg)
And i still saw no sky/sun or cloud i should see.
Step 4
 For reference i took the same screenshot on a default fabric build i did with just sodium instead of rubidium and iris shader instead of oculus, but no other mod , no ressourcepack and ofcourse same shader with same setting to show what it should look like.
![sodium+iris with shader](https://user-images.githubusercontent.com/24650325/164264980-8eec613c-0d00-4816-b2b1-c578cc5c6f1e.jpg)
As you can see on the fabric build using sodium and iris i can cleary see the sky / cloud / sun, from underwater .

Thats why i think it's a bug that rubidium remove all sky related information while you are under water, if it's intended please let me know, but it would be sad. 

And yea i could keep the fabric build but i made a modpack with lot of thing i really like on the forge loader that why i would like rubidium to work great too if it a bug.

**Comment by paradoxuum** [comment]
This is intentional; there's a comment on the `MixinWorldRenderer#preRenderSky` method that explains the reasoning behind this.

It prevents the sky from being seen through chunks that are culled by fog occlusion - the downside to this is that the sky is not rendered when underwater, though the comment states that is intentional and that it also matches Bedrock edition.

This is present in the 1.19 version of Sodium as well, so I would assume that Iris allows the sky to be rendered. You'd be better of making an issue in the [Oculus](https://github.com/Asek3/Oculus) repository instead.
